// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5f3f08eb-c06e-43e3-8f6e-cd7addd645b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NGJCyOXnJ",
    "aws_user_pools_web_client_id": "7ml59iphjbig4gt1k55hs0a4l0",
    "oauth": {}
};


export default awsmobile;
